version: "3.8"

services:
  app:
    build: .
    container_name: cuba_app
    ports:
      - "9292:9292"
    depends_on:
      - redis
    environment:
      - RACK_ENV=production
      - REDIS_URL=redis://redis:6379/0
    volumes:
      - .:/app

  redis:
    image: redis:latest
    container_name: cuba_redis
    ports:
      - "6379:6379"
    restart: always
