version: "3.8"

services:
  app:
    build: .
    container_name: cuba_app
    ports:
      - "9292:9292"
    depends_on:
      - redis
      - sidekiq
    environment:
      - RACK_ENV=production
      - REDIS_URL=redis://cuba_redis:6379/0
      - SECRET_KEY=tu_clave_secreta_super_segura
    volumes:
      - .:/app

  redis:
    image: redis:latest
    container_name: cuba_redis
    ports:
      - "6395:6379"  
    restart: always

  sidekiq:
    build: .
    container_name: cuba_sidekiq
    depends_on:
      - redis
    environment:
      - RACK_ENV=production
      - REDIS_URL=redis://cuba_redis:6379/0
    command: ["bundle", "exec", "sidekiq", "-r", "./app.rb"]
    volumes:
      - .:/app
