openapi: "3.0.0"
info:
  version: 1.0.0
  title: FUDO Semi Senior Challenge API
paths:
  /login:
    post:
      summary: Iniciar sesión de un usuario
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                password:
                  type: string
      responses:
        "200":
          description: Inicio de sesión exitoso
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string
        "401":
          description: Credenciales inválidas
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
  /register:
    post:
      summary: Registrar un nuevo usuario
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                password:
                  type: string
      responses:
        "201":
          description: Usuario registrado exitosamente
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  user:
                    type: object
        "400":
          description: Error en el registro
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                  details:
                    type: array
                    items:
                      type: string
  /products:
    get:
      summary: Retorna una lista de productos
      parameters:
        - in: header
          name: Authorization
          schema:
            type: string
          required: true
        - in: header
          name: Accept-Encoding
          schema:
            type: string
          description: Solicitar codificación gzip para la respuesta (opcional)
      responses:
        "200":
          description: Un arreglo JSON de productos
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
        "401":
          description: Token no válido
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
    post:
      summary: Crear un producto de forma asíncrona
      parameters:
        - in: header
          name: Authorization
          schema:
            type: string
          required: true
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
      responses:
        "201":
          description: Producto en proceso de creación
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
        "401":
          description: Token no válido
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
  /AUTHORS:
    get:
      summary: Obtener información del autor
      responses:
        "200":
          description: Información del autor de la app
          content:
            text/plain:
              schema:
                type: string
