name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest

    services:
      redis:
        image: redis
        ports:
          - 6379:6379

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.3.0
          bundler-cache: true

      - name: Install dependencies
        run: bundle install

      - name: Build and start the app using Docker Compose
        run: |
          docker compose up -d --build

      - name: Wait for services to be ready
        run: sleep 10  # Da tiempo a que Redis y la App se inicien

      - name: Run Sidekiq
        run: docker compose exec -T app bundle exec sidekiq -r ./config/sidekiq.rb

      - name: Run tests
        env:
          RACK_ENV: test
          REDIS_URL: redis://redis:6379/1
        run: docker compose exec -T app bundle exec rspec

      - name: Stop services after tests
        if: always()
        run: docker compose down

  deploy:
    name: Deploy to Production
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
