name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest

    services:
      redis:
        image: redis
        ports:
          - 6379:6379

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.3.0
          bundler-cache: true

      - name: Install dependencies
        run: bundle install

      - name: Build and start the app using Docker Compose
        run: docker compose up -d --build

      - name: Wait for services to be ready
        run: |
          echo "Esperando a que Redis y la aplicación estén listos..."
          for i in {1..10}; do
            if docker compose exec -T app curl -s http://localhost:9292 > /dev/null && \
               docker compose exec -T redis redis-cli ping | grep -q PONG; then
              echo "Todos los servicios están listos."
              exit 0
            fi
            echo "Intento $i: Servicios aún no disponibles..."
            sleep 5
          done
          echo "Error: Los servicios no se iniciaron correctamente."
          exit 1

      - name: Run Sidekiq
        run: docker compose exec -T sidekiq bundle exec sidekiq -r ./app.rb

      - name: Run tests
        env:
          RACK_ENV: test
          REDIS_URL: redis://redis:6379/1
        run: docker compose exec -T app bundle exec rspec

      - name: Stop services after tests
        if: always()
        run: docker compose down

  deploy:
    name: Deploy to Production
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
